// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of RadioStream_List ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class RadioStream_ListViewModel : ViewModelsBase.VMBase, IViewModels.IRadioStream_ListViewModel
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly Repositories.IRadioStreamer_Streamer _radioStreamer_Streamer;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="RadioStream_ListViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="radioStreamer_Streamer">The Radio Streamer_ Streamer.</param>
        public RadioStream_ListViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, Repositories.IRadioStreamer_Streamer radioStreamer_Streamer)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_radioStreamer_Streamer = radioStreamer_Streamer;
        }
		
	
		private ObservableCollection<Entities.StreamerSchema> _radioStream_ListListControlCollection;

        /// <summary>
        /// RadioStream_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<Entities.StreamerSchema> RadioStream_ListListControlCollection
        {
            get
            {
				
                if(_radioStream_ListListControlCollection == null)
					_radioStream_ListListControlCollection = _radioStreamer_Streamer.GetData();
				return _radioStream_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _radioStream_ListListControlCollection, value);
            }
        }
	
		private int _radioStream_ListListControlCollectionPageNumber;

        /// <summary>
        /// RadioStream_ListListControlCollectionPageNumber property.
        /// </summary>		
        public int RadioStream_ListListControlCollectionPageNumber
        {
            get
            {
				return _radioStream_ListListControlCollectionPageNumber;
            }
            set
            {
                SetProperty(ref _radioStream_ListListControlCollectionPageNumber, value);
            }
        }
	
		private Entities.StreamerSchema _selectedRadioStream_ListListControlCollection;

        /// <summary>
        /// SelectedRadioStream_ListListControlCollection property.
        /// </summary>		
        public Entities.StreamerSchema SelectedRadioStream_ListListControlCollection
        {
            get
            {
				return _selectedRadioStream_ListListControlCollection;
            }
            set
            {
                _selectedRadioStream_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.IRadioStream_DetailViewModel>(_selectedRadioStream_ListListControlCollection);
            }
        }
	    /// <summary>
        /// IsInternetAvailable property.
        /// </summary>		
        public override Visibility IsInternetAvailable
        {
	      get
          {
				return Visibility.Collapsed; 
           }
		}

        /// <summary>
        /// Delegate method for the GetRadioStream_ListListControlCollectionCommand command.
        /// </summary>
        public  void GetRadioStream_ListListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				GetRadioStream_ListListControlCollectionData(pageNumber);
        }
		

        private ICommand _getRadioStream_ListListControlCollectionCommand;

        /// <summary>
        /// Gets the GetRadioStream_ListListControlCollectionCommand command.
        /// </summary>
        public ICommand GetRadioStream_ListListControlCollectionCommand
        {
            get { return _getRadioStream_ListListControlCollectionCommand = _getRadioStream_ListListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(GetRadioStream_ListListControlCollectionCommandDelegate); }
        }

        private void GetRadioStream_ListListControlCollectionData(int pageNumber = 0)
        {
				RadioStream_ListListControlCollectionPageNumber = pageNumber;

                if (pageNumber == 0)
				{
					var items = _radioStreamer_Streamer.GetData(pageNumber);
                    RadioStream_ListListControlCollection = items;
				}
                else   
				{
					var items = _radioStreamer_Streamer.GetData(pageNumber);
                    foreach (var item in items)                    
                        RadioStream_ListListControlCollection.Add(item);
				}
		}
    }
}
