// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of RadioStream_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class RadioStream_DetailViewModel : ViewModelsBase.VMBase, IViewModels.IRadioStream_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.RadioStreamer_Streamer _radioStreamer_Streamer;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="RadioStream_DetailViewModel" /> class.
        /// </summary>
        /// <param name="radioStreamer_Streamer">The Radio Streamer_ Streamer.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public RadioStream_DetailViewModel(Repositories.RadioStreamer_Streamer radioStreamer_Streamer, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_radioStreamer_Streamer = radioStreamer_Streamer;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private Entities.StreamerSchema _currentStreamerSchema;

        /// <summary>
        /// CurrentStreamerSchema property.
        /// </summary>		
        public Entities.StreamerSchema CurrentStreamerSchema
        {
            get
            {
				return _currentStreamerSchema;
            }
            set
            {
                SetProperty(ref _currentStreamerSchema, value);
            }
        }
	
		private bool _hasNextpanoramaRadioStream_Detail0;

        /// <summary>
        /// HasNextpanoramaRadioStream_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramaRadioStream_Detail0
        {
            get
            {
				return _hasNextpanoramaRadioStream_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramaRadioStream_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramaRadioStream_Detail0;

        /// <summary>
        /// HasPreviouspanoramaRadioStream_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramaRadioStream_Detail0
        {
            get
            {
				return _hasPreviouspanoramaRadioStream_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramaRadioStream_Detail0, value);
            }
        }
	    /// <summary>
        /// IsInternetAvailable property.
        /// </summary>		
        public override Visibility IsInternetAvailable
        {
	      get
          {
				return Visibility.Collapsed; 
           }
		}

        /// <summary>
        /// Delegate method for the TextToSpeechRadioStream_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechRadioStream_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentStreamerSchema.Title + " " + CurrentStreamerSchema.Subtitle);
        }
		

        private ICommand _textToSpeechRadioStream_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechRadioStream_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechRadioStream_DetailStaticControlCommand
        {
            get { return _textToSpeechRadioStream_DetailStaticControlCommand = _textToSpeechRadioStream_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechRadioStream_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareRadioStream_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareRadioStream_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentStreamerSchema.Title, CurrentStreamerSchema.Subtitle, "", CurrentStreamerSchema.Image);
        }
		

        private ICommand _shareRadioStream_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareRadioStream_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareRadioStream_DetailStaticControlCommand
        {
            get { return _shareRadioStream_DetailStaticControlCommand = _shareRadioStream_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareRadioStream_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartRadioStream_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartRadioStream_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.IRadioStream_DetailViewModel), CreateTileInfoRadioStream_DetailStaticControl());
        }
		

        private ICommand _pinToStartRadioStream_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartRadioStream_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartRadioStream_DetailStaticControlCommand
        {
            get { return _pinToStartRadioStream_DetailStaticControlCommand = _pinToStartRadioStream_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartRadioStream_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the NextpanoramaRadioStream_Detail0 command.
        /// </summary>
        public  void NextpanoramaRadioStream_Detail0Delegate() 
        {
			var next =  _radioStreamer_Streamer.Next(CurrentStreamerSchema);

			if(next != null)
				CurrentStreamerSchema = next;

			RefreshHasPrevNext();
        }
		

        private ICommand _nextpanoramaRadioStream_Detail0;

        /// <summary>
        /// Gets the NextpanoramaRadioStream_Detail0 command.
        /// </summary>
        public ICommand NextpanoramaRadioStream_Detail0
        {
            get { return _nextpanoramaRadioStream_Detail0 = _nextpanoramaRadioStream_Detail0 ?? new ViewModelsBase.DelegateCommand(NextpanoramaRadioStream_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the PreviouspanoramaRadioStream_Detail0 command.
        /// </summary>
        public  void PreviouspanoramaRadioStream_Detail0Delegate() 
        {
			var prev =  _radioStreamer_Streamer.Previous(CurrentStreamerSchema);

			if(prev != null)
				CurrentStreamerSchema = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramaRadioStream_Detail0;

        /// <summary>
        /// Gets the PreviouspanoramaRadioStream_Detail0 command.
        /// </summary>
        public ICommand PreviouspanoramaRadioStream_Detail0
        {
            get { return _previouspanoramaRadioStream_Detail0 = _previouspanoramaRadioStream_Detail0 ?? new ViewModelsBase.DelegateCommand(PreviouspanoramaRadioStream_Detail0Delegate); }
        }

        private void RefreshHasPrevNext()
        {
            HasPreviouspanoramaRadioStream_Detail0 = _radioStreamer_Streamer.HasPrevious(CurrentStreamerSchema);
			HasNextpanoramaRadioStream_Detail0 = _radioStreamer_Streamer.HasNext(CurrentStreamerSchema);
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is Entities.StreamerSchema)) { return; }
                
                CurrentStreamerSchema = value as Entities.StreamerSchema;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the RadioStream_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoRadioStream_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentStreamerSchema.Id.ToString(),
                Title = CurrentStreamerSchema.Title,
                BackTitle = CurrentStreamerSchema.Title,
                BackContent = CurrentStreamerSchema.Subtitle,
                Count = 0,
                BackgroundImagePath = CurrentStreamerSchema.Image,
                BackBackgroundImagePath = CurrentStreamerSchema.Image,
                LogoPath = "Logo-d8c5800e-008d-427f-8760-3d6e8ed66cfb.png"
            };
            return tileInfo;
        }
    }
}
