// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	AboutPageCS.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Net;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Navigation;
using Entities = WPAppStudio.Entities;
using Ioc = WPAppStudio.Ioc;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Microsoft.Phone.Controls;
using Microsoft.Phone.Shell;
using MyToolkit.Paging;
using Repositories = WPAppStudio.Repositories;
using WPAppStudio;
using WPAppStudio.Shared;


namespace WPAppStudio.View
{
    /// <summary>
    /// Phone application page for About.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class About : PhoneApplicationPage
    {       
        /// <summary>
        /// Initializes the phone application page for About and all its components.
        /// </summary>
        public About()
        {
            InitializeComponent();
            if (Resources.Contains("PanoramaMenuSection_Menu0AppBar"))
                PhonePage.SetApplicationBar(this, Resources["PanoramaMenuSection_Menu0AppBar"] as BindableApplicationBar);  
		}

        // License Terms
        private void Button_Click(object sender, System.Windows.RoutedEventArgs e)
        {
            NavigationService.Navigate(new Uri("/View/LicenseTerms.xaml", UriKind.Relative));
        }

        // Changelog
        private void Button_Click_1(object sender, System.Windows.RoutedEventArgs e)
        {
            NavigationService.Navigate(new Uri("/View/Changelog.xaml", UriKind.Relative));
        }

        // Privacy Info
        private void Button_Click_2(object sender, System.Windows.RoutedEventArgs e)
        {
            NavigationService.Navigate(new Uri("/View/PrivacyInfo.xaml", UriKind.Relative));
        }

        // Machine generated code copied from MenuSection_Menu
        private void panoramaMenuSection_Menu_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            InitializeAppBarpanoramaMenuSection_Menu(PanoramaMenuSection_Menu.SelectedItem as PanoramaItem);
        }

        private void InitializeAppBarpanoramaMenuSection_Menu(PanoramaItem panoramaItem)
        {
            if (Resources.Contains(panoramaItem.Name + "AppBar"))
            {
                PhonePage.SetApplicationBar(this, Resources[panoramaItem.Name + "AppBar"] as BindableApplicationBar);
                ApplicationBar.IsVisible = true;
            }
            else if (ApplicationBar != null)
                ApplicationBar.IsVisible = false;
        }

        /// <summary>
        /// Called when the page becomes the active page.
        /// </summary>
        /// <param name="e">Contains information about the navigation done.</param>
        protected override void OnNavigatedTo(NavigationEventArgs e)
        {
            base.OnNavigatedTo(e);
            MenuSection_MenuMenuControl.SelectedItem = null;
        }

        // Quit Application to reduce Memory consuption

    }
}
