// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	AboutPageCS.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using System.Windows.Controls;
using Microsoft.Phone.Controls;

namespace WPAppStudio.View
{
    /// <summary>
    /// Phone application page for About.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class About : PhoneApplicationPage
    {       
        /// <summary>
        /// Initializes the phone application page for About and all its components.
        /// </summary>
        public About()
        {
            InitializeComponent();        
		}
    }
}
