// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	AboutPageCS.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using System.Windows.Controls;
using Microsoft.Phone.Controls;
using System;

namespace WPAppStudio.View
{
    /// <summary>
    /// Phone application page for About.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class About : PhoneApplicationPage
    {       
        /// <summary>
        /// Initializes the phone application page for About and all its components.
        /// </summary>
        public About()
        {
            InitializeComponent();        
		}

        // License Terms
        private void Button_Click(object sender, System.Windows.RoutedEventArgs e)
        {
            NavigationService.Navigate(new Uri("/View/LicenseTerms.xaml", UriKind.Relative));
        }

        // Changelog
        private void Button_Click_1(object sender, System.Windows.RoutedEventArgs e)
        {
            NavigationService.Navigate(new Uri("/View/Changelog.xaml", UriKind.Relative));
        }

        // Privacy Info
        private void Button_Click_2(object sender, System.Windows.RoutedEventArgs e)
        {
            NavigationService.Navigate(new Uri("/View/PrivacyInfo.xaml", UriKind.Relative));
        }
    }
}
