// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// RadioStream_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IRadioStream_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentStreamerSchema property.
        /// </summary>
		Entities.StreamerSchema CurrentStreamerSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaRadioStream_Detail0 property.
        /// </summary>
		bool HasNextpanoramaRadioStream_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaRadioStream_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaRadioStream_Detail0 { get; set; }
	    /// <summary>
        /// IsInternetAvailable property.
        /// </summary>		
        Visibility IsInternetAvailable { get; }
        
        /// <summary>
        /// Gets the TextToSpeechRadioStream_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechRadioStream_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareRadioStream_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareRadioStream_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartRadioStream_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartRadioStream_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaRadioStream_Detail0 command.
        /// </summary>
		ICommand NextpanoramaRadioStream_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaRadioStream_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaRadioStream_Detail0 { get; }

	}
}
