// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// RadioStreamer_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IRadioStreamer_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentStreamerSchema property.
        /// </summary>
		Entities.StreamerSchema CurrentStreamerSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaRadioStreamer_Detail0 property.
        /// </summary>
		bool HasNextpanoramaRadioStreamer_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaRadioStreamer_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaRadioStreamer_Detail0 { get; set; }
	    /// <summary>
        /// IsInternetAvailable property.
        /// </summary>		
        Visibility IsInternetAvailable { get; }
        
        /// <summary>
        /// Gets the TextToSpeechRadioStreamer_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechRadioStreamer_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareRadioStreamer_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareRadioStreamer_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartRadioStreamer_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartRadioStreamer_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaRadioStreamer_Detail0 command.
        /// </summary>
		ICommand NextpanoramaRadioStreamer_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaRadioStreamer_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaRadioStreamer_Detail0 { get; }

	}
}
