// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IDataSource.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// RadioStreamer_Streamer interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IRadioStreamer_Streamer
    {
		ObservableCollection<Entities.StreamerSchema> GetData(int pageNumber = 0);
		ObservableCollection<Entities.StreamerSchema> Search(FilterSpecification filter);
		bool HasPrevious(Entities.StreamerSchema current);
		bool HasNext(Entities.StreamerSchema current);
		Entities.StreamerSchema Previous(Entities.StreamerSchema current);
		Entities.StreamerSchema Next(Entities.StreamerSchema current);
    }
}
