// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ServiceLocator.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using IIoc = WPAppStudio.Ioc.Interfaces;
using Ioc = WPAppStudio.Ioc;
using IViewModels = WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.Services
{
    /// <summary>
    /// Implementation of the ViewModel locator service based on IoC.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class ViewModelLocatorService
    {
        // IoC container
        private readonly IIoc.IContainer _container;

        /// <summary>
        /// Initializes a new instance of the <see cref="ViewModelLocatorService" /> class.
        /// </summary>
        public ViewModelLocatorService()
        {
            _container = new Ioc.Container();
        }
		
		/// <summary>
        /// Resolve a service of type T
        /// </summary>
        /// <typeparam name="T">Type of the service.</typeparam>
        /// <returns></returns>
        public T ResolveService<T>()
        {
            return _container.Resolve<T>();
        }

        /// <summary>
        /// Gets the reference to a MenuSection_MenuViewModel.
        /// </summary>
		public IViewModels.IMenuSection_MenuViewModel MenuSection_MenuViewModel
        {
            get { return _container.Resolve<IViewModels.IMenuSection_MenuViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a RadioStreamer_DetailViewModel.
        /// </summary>
		public IViewModels.IRadioStreamer_DetailViewModel RadioStreamer_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.IRadioStreamer_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a RadioStream_ListViewModel.
        /// </summary>
		public IViewModels.IRadioStream_ListViewModel RadioStream_ListViewModel
        {
            get { return _container.Resolve<IViewModels.IRadioStream_ListViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a RadioStream_DetailViewModel.
        /// </summary>
		public IViewModels.IRadioStream_DetailViewModel RadioStream_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.IRadioStream_DetailViewModel>(); }
        }
		/// <summary>
        /// Gets the reference to a AboutViewModel.
        /// </summary>
		public IViewModels.IAboutViewModel AboutViewModel
        {
            get { return _container.Resolve<IViewModels.IAboutViewModel>(); }
        }
		
		/// <summary>
        /// Gets the reference to a LicenseViewModel.
        /// </summary>
		public IViewModels.ILicenseViewModel LicenseViewModel
        {
            get { return _container.Resolve<IViewModels.ILicenseViewModel>(); }
        }
    }
}
