// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   LicensePageCS.tt
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using System.Windows.Controls;
using Microsoft.Phone.Controls;

namespace WPAppStudio.View
{
    /// <summary>
    /// Phone application page for License.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class License : PhoneApplicationPage
    {       
        /// <summary>
        /// Initializes the phone application page for License and all its components.
        /// </summary>
        public License()
        {
            InitializeComponent();        
		}
    }
}
